name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 5.101.159.131
  SERVER_USER: novato1v
  SERVER_PATH: /home/n/novato1v/otal-estate.ru/public_html

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Actions checkout
      - uses: actions/checkout@v3
        with:
          node-version: '18.x'

      # Deploy
      - name: Connect on remote server and deploy
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{env.SERVER_HOST}}
          user: ${{env.SERVER_USER}}
          private_key: ${{secrets.KEY}}
          command: |
            cd ${{env.SERVER_PATH}};
            git checkout master;
            git reset --hard
            git pull origin master;
            cd backend
            date +%s > version.txt