name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: novato1v.beget.tech
  SERVER_USER: novato1v
  SERVER_PORT: 22
  SERVER_PASS: F8t5vkza
  SERVER_PATH: /home/n/novato1v/otal-estate.ru/public_html

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Actions checkout
      - uses: actions/checkout@v3
        with:
          node-version: '18.x'

      # Deploy
      - name: Connect on remote server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{env.SERVER_HOST}}
          port: ${{env.SERVER_PORT}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASS}}
          key: ${{secrets.KEY}}
          script: |
            cd ${{env.SERVER_PATH}};
            git checkout master;
            git reset --hard
            git pull origin master;
            cd backend
            sed -i '1s/.*/$(date "+%s")/' version.txt
